### ISSUE TITLE
pip3 install tree/ fails missing README.md

### ISSUE THREAD

**Issue by stain** [morloc-project/examples#6]
Attempting to resolve #5  by moving the `Dockerfile` into folder `workflow-comparisons/flu-case-study` I get a new error:

```
STEP 9/20: RUN pip3 install treebase/ tree/ retrieveFlu/
Processing ./treebase
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Processing ./tree
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/cases-lib/tree/setup.py", line 3, in <module>
          with open("README.md", "r") as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Error: error building at STEP "RUN pip3 install treebase/ tree/ retrieveFlu/": error while running runtime: exit status 1
```

It seems the README is missing from `workflow-comparisons/flu-case-study/modules/tree`

```
(base) stain@xenamint:~/src/examples/workflow-comparisons/flu-case-study$ ls modules/tree
setup.py  tree
(base) stain@xenamint:~/src/examples/workflow-comparisons/flu-case-study$ ls modules/treebase/
README.md  setup.py  src  tests

```

**Comment by arendsee** [comment]
@stain You are quite right, thanks for the issue report! Let me know if this fixes the issue.
